apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: {{ .Values.namespace }}
  labels:
    app: podinfo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--port={{ .Values.container.port }}"
            - "--host=0.0.0.0"
            - "--level={{ .Values.container.logLevel }}"
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
